# Generated by Django 4.0.3 on 2022-10-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hat',
            old_name='style_name',
            new_name='style',
        ),
    ]
