# Generated by Django 4.0.3 on 2022-10-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0003_remove_locationvo_name_locationvo_section_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationvo',
            name='closet_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
