# Generated by Django 4.0.3 on 2022-10-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_binvo_closet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
